[providers]
python = {}

[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
